SocialNetwork/Controllers/MainController.cs
using SocialNetwork.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialNetwork.Controllers
{
    public class MainController : Controller
    {
        public ActionResult Index()
        {
            if (users.isUserLoggedIn() != true) // если пользователь не находится в аккаунте
            {
                ViewBag.ViewingUser = null;
            }
            else
            {
                int user_id = Convert.ToInt32(Session["id"]);
                ViewBag.ViewingUser = users.getUserFromUserId(user_id);
            }
            return View();
        }

        public ActionResult Registration()
        {
            if (users.isUserLoggedIn() == true) // если пользователь находится в аккаунте
            {
                return RedirectToAction("Viewing", "Users"); // перенаправляем пользователя в его профиль
            }
            else
            {
                List<string> errors = new List<string>();

                //try
                {
                    if (Request.Form["ok"] != null)
                    {
                        string login = Request.Form["login"];
                        string name = Request.Form["name"];
                        string password = Request.Form["password"];
                        string password_2 = Request.Form["password_2"];
                        string secret_question = Request.Form["secret_question"];
                        string secret_answer = Request.Form["secret_answer"];

                        MyFunctions.checkLogin(login, ref errors);
                        if (name != "")
                        {
                            MyFunctions.checkName(name, ref errors);
                        }
                        MyFunctions.checkPassword(password, ref errors);
                        MyFunctions.checkPassword2(password, password_2, ref errors);
                        MyFunctions.checkSecretQuestion(secret_question, secret_answer, ref errors);
                        MyFunctions.checkSecretAnswer(secret_answer, false, ref errors);

                        if (errors.Count == 0)
                        {
                            MyFunctions.checkLoginNotExistInDatabase(login, ref errors);

                            if (errors.Count == 0)
                            {
                                users user = new users(); // новый пользователь
                                user.login = login;
                                user.name = name;
                                user.password_sha512 = users.generateSha512(password);
                                if (secret_question != "") // если был указан секретный вопрос - сохраняем и его, ответ на него
                                {
                                    user.secret_question = secret_question;
                                    user.secret_answer_sha512 = users.generateSha512(secret_answer);
                                }
                                user.permissions_rank = 0; // ранг: 0 – пользователь; 1 – модератор; 2 – администратор; 3 – главный администратор
                                user.registration_datetime_int = (int)((DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalSeconds);

                                MyFunctions.database.users.Add(user); // добавляем пользователя в БД
                                MyFunctions.database.SaveChanges(); // сохраняем БД

                                // после добавления пользователя в БД, добавим для него имя и уникальное специальное имя
                                users user_found = MyFunctions.database.users.Where(p => (p.login == user.login) && (p.password_sha512 == user.password_sha512)).FirstOrDefault();
                                user.special_name = "id" + user_found.id;

                                if (user.name == "")
                                {
                                    user.name = user.special_name;
                                }

                                MyFunctions.database.SaveChanges(); // сохраняем БД
                                users.SaveSession(user);

                                return RedirectToAction("Viewing", "Users"); // перенаправляем пользователя в его профиль
                            }
                        }
                    }
                }
                //catch
                {
                //    errors.Add("Недопустимый текст! Можно вводить только обычный текст, использование HTML-тегов не разрешено!");
                }

                ViewBag.Errors = errors;
                return View();
            }
        }

        public ActionResult Authorization()
        {
            if (users.isUserLoggedIn() == true) // если пользователь находится в аккаунте
            {
                return RedirectToAction("Viewing", "Users"); // перенаправляем пользователя в его профиль
            }
            else
            {
                List<string> errors = new List<string>();

                try
                {
                    if (Request.Form["ok"] != null)
                    {
                        string login = Request.Form["login"];
                        string password = Request.Form["password"];

                        MyFunctions.checkLogin(login, ref errors);
                        MyFunctions.checkPassword(password, ref errors);

                        if (errors.Count == 0)
                        {
                            string password_sha512 = users.generateSha512(password);

                            users user_found = MyFunctions.checkLoginAndPasswordSha512ExistInDatabase(login, password_sha512, ref errors);

                            if (errors.Count == 0)
                            {
                                users.SaveSession(user_found); // сохраняем сессию
                                return RedirectToAction("Viewing", "Users"); // перенаправляем пользователя в его профиль
                            }
                        }
                    }
                }
                catch
                {
                    errors.Add("Недопустимый текст! Можно вводить только обычный текст, использование HTML-тегов не разрешено!");
                }

                ViewBag.Errors = errors;
                return View();
            }
        }

        public ActionResult PasswordRecovery()
        {
            if (users.isUserLoggedIn() == true) // если пользователь находится в аккаунте
            {
                return RedirectToAction("Viewing", "Users"); // перенаправляем пользователя в его профиль
            }
            else
            {
                List<string> errors = new List<string>();

                // стадия ввода логина
                try
                {
                    if ((Request.Form["next"] != null) || (Request.Form["next_2"] != null) || (Request.Form["ok"] != null))
                    {
                        string login = Request.Form["login"];

                        MyFunctions.checkLogin(login, ref errors);

                        if (errors.Count == 0)
                        {
                            users user_found = MyFunctions.checkLoginExistInDatabase(login, ref errors);
                            ViewBag.IsLoginCorrect = false;
                            if (errors.Count == 0)
                            {
                                ViewBag.IsLoginCorrect = true;

                                ViewBag.SecretQuestion = user_found.secret_question; // получение текста секретного вопроса из БД

                                // стадия ввода ответа на секретный вопрос
                                if ((Request.Form["next_2"] != null) || (Request.Form["ok"] != null))
                                {
                                    string secret_answer = Request.Form["secret_answer"];
                                    string secret_answer_sha512 = users.generateSha512(secret_answer);

                                    MyFunctions.checkSecretAnswer(secret_answer, true, ref errors);

                                    ViewBag.IsSecretAnswerCorrect = false;
                                    if (errors.Count == 0)
                                    {
                                        user_found = MyFunctions.checkSecretAnswerSha512InDatabase(secret_answer_sha512, login, ref errors);
                                        if (errors.Count == 0)
                                        {
                                            ViewBag.IsSecretAnswerCorrect = true;

                                            // стадия ввода нового пароля
                                            if (Request.Form["ok"] != null)
                                            {
                                                string password = Request.Form["password"];
                                                string password_2 = Request.Form["password_2"];

                                                MyFunctions.checkPassword(password, ref errors);
                                                MyFunctions.checkPassword2(password, password_2, ref errors);
                                                if (errors.Count == 0)
                                                {
                                                    string password_sha512 = users.generateSha512(password);
                                                    user_found.password_sha512 = password_sha512; // меняем пароль пользователя в БД
                                                    MyFunctions.database.SaveChanges(); // сохраняем БД
                                                    users.SaveSession(user_found); // сохраняем сессию

SocialNetwork/Views/Main/Authorization.cshtml
@{
    ViewBag.Title = "Авторизация";
}

<form method="POST" class="form_two_columns">
    <table>
        <tr>
            <td class="td_value_text">
                <b>Логин <span class="required_asterisk">*</span>:<b>
            </td>
            <td>
                @{
                    ViewContext.Writer.Write("<input type=\"text\" name=\"login\" maxlength=\"32\" size=\"32\" value=\"");
                    string text = Request.Unvalidated.Form.Get("login");
                    if (text == null)
                    {
                        text = ViewBag.login;
                    }
                    ViewContext.Writer.Write(text);
                    ViewContext.Writer.Write("\"/>");
                }
            </td>
        </tr>
        <tr>
            <td class="td_value_text">
                <b>Пароль <span class="required_asterisk">*</span>:<b>
            </td>
            <td>
                @{
                    ViewContext.Writer.Write("<input type=\"password\" name=\"password\" maxlength=\"128\" size=\"32\" value=\"");
                    text = Request.Unvalidated.Form.Get("password");
                    if (text == null)
                    {
                        text = ViewBag.password;
                    }
                    ViewContext.Writer.Write(text);
                    ViewContext.Writer.Write("\"/>");
                }
            </td>
        </tr>
        @if ((ViewBag.Errors != null) && (ViewBag.Errors.Count != 0))
        {
            <tr>
                <td colspan="2" class="td_errors">
                    @foreach (string error in ViewBag.Errors)
                    {
                        @error<br />
                    }
                </td>
            </tr>
        }
        <tr>
            <td colspan="2" class="td_buttons">
                <input type="submit" name="ok" value="Войти" /><br />
                @Html.ActionLink("Регистрация", "Registration", "Main")<br />
                @Html.ActionLink("Восстановление пароля", "PasswordRecovery", "Main")
            </td>
        </tr>
    </table>
</form>

SocialNetwork/Views/Main/Index.cshtml
@{
    ViewBag.Title = "Главная";
}

<div class="center_content">
    @if (SocialNetwork.Models.users.isUserLoggedIn() != true) // если пользователь не находится в аккаунте
    {
        <p>Добро пожаловать!</p>
        <br />
        @Html.ActionLink("Регистрация", "Registration", "Main", null, new { @class = "my_button" })
        @Html.ActionLink("Авторизация", "Authorization", "Main", null, new { @class = "my_button" })
    }
    else
    {
        if (@ViewBag.ViewingUser.name != null)
        {
            <p>Добро пожаловать, @ViewBag.ViewingUser.name!</p>
        }
        else
        {
            <p>Добро пожаловать!</p>
        }
    }
</div>

SocialNetwork/Views/Main/Logout.cshtml
@{
    ViewBag.Title = "Выход из аккаунта...";
}

SocialNetwork/Views/Main/PasswordRecovery.cshtml
@{
    ViewBag.Title = "Восстановление пароля";
}

<form method="POST" class="form_two_columns">
    <table>
        <tr>
            <td class="td_value_text">
                <b>Логин <span class="required_asterisk">*</span>:<b>
            </td>
            <td>
                @{
                    ViewContext.Writer.Write("<input type=\"text\" name=\"login\" maxlength=\"32\" size=\"32\" value=\"");
                    string text = Request.Unvalidated.Form.Get("login");
                    if (text == null)
                    {
                        text = ViewBag.login;
                    }
                    ViewContext.Writer.Write(text);
                    ViewContext.Writer.Write("\"/>");
                }
            </td>
        </tr>
        @if (ViewBag.IsLoginCorrect == true)
        {
            <tr>
                <td colspan="2" class="td_text">
                    <b>Секретный вопрос:<b><br />
                    @ViewBag.SecretQuestion
                </td>
            </tr>
            <tr>
                <td class="td_value_text">
                    <b>Ответ на секретный вопрос <span class="required_asterisk">*</span>:<b>
                </td>
                <td>
                    @{
                        ViewContext.Writer.Write("<input type=\"text\" name=\"secret_answer\" maxlength=\"128\" size=\"32\" value=\"");
                        text = Request.Unvalidated.Form.Get("secret_answer");
                        if (text == null)
                        {
                            text = ViewBag.secret_answer;
                        }
                        ViewContext.Writer.Write(text);
                        ViewContext.Writer.Write("\"/>");
                    }
                </td>
            </tr>
        }
        @if (ViewBag.IsSecretAnswerCorrect == true)
        {
            <tr>
                <td class="td_value_text">
                    <b>Новый пароль <span class="required_asterisk">*</span>:<b>
                </td>
                <td>
                    @{
                        ViewContext.Writer.Write("<input type=\"text\" name=\"password\" maxlength=\"128\" size=\"32\" value=\"");
                        text = Request.Unvalidated.Form.Get("password");
                        if (text == null)
                        {
                            text = ViewBag.password;
                        }
                        ViewContext.Writer.Write(text);
                        ViewContext.Writer.Write("\"/>");
                    }
                </td>
            </tr>
            <tr>
                <td class="td_value_text">
                    <b>Подтверждение нового пароля <span class="required_asterisk">*</span>:<b>
                </td>
                <td>
                    @{
                        ViewContext.Writer.Write("<input type=\"text\" name=\"password_2\" maxlength=\"128\" size=\"32\" value=\"");
                        text = Request.Unvalidated.Form.Get("password_2");
                        if (text == null)
                        {
                            text = ViewBag.password_2;
                        }
                        ViewContext.Writer.Write(text);
                        ViewContext.Writer.Write("\"/>");
                    }
                </td>
            </tr>
        }
        @if ((ViewBag.Errors != null) && (ViewBag.Errors.Count != 0))
        {
            <tr>
                <td colspan="2" class="td_errors">
                    @foreach (string error in ViewBag.Errors)
                    {
                        @error<br />
                    }
                </td>
            </tr>
        }
        <tr>
            <td colspan="2" class="td_buttons">
                @if ((ViewBag.IsLoginCorrect == null) || (ViewBag.IsLoginCorrect == false))
                {
                    <input type="submit" name="next" value="Далее" /><br />
                }
                else if ((ViewBag.IsLoginCorrect == true) && ((ViewBag.IsSecretAnswerCorrect == null) || (ViewBag.IsSecretAnswerCorrect == false)))
                {
                    <input type="submit" name="next_2" value="Далее" /><br />
                }
                else if (ViewBag.IsSecretAnswerCorrect == true)
                {
                    <input type="submit" name="ok" value="Восстановить пароль" /><br />
                }
                @Html.ActionLink("Авторизация", "Authorization", "Main")<br />
                @Html.ActionLink("Регистрация", "Registration", "Main")
            </td>
        </tr>
    </table>
</form>

SocialNetwork/Views/Main/Registration.cshtml
@{
    ViewBag.Title = "Регистрация";
}

<form method="POST" class="form_two_columns">
    <table>
        <tr>
            <td class="td_value_text">
                <b>Логин <span class="required_asterisk">*</span>:<b>
            </td>
            <td>
                @{
                    ViewContext.Writer.Write("<input type=\"text\" name=\"login\" maxlength=\"32\" size=\"32\" value=\"");
                    string text = Request.Unvalidated.Form.Get("login");
                    if (text == null)
                    {
                        text = ViewBag.login;
                    }
                    ViewContext.Writer.Write(text);
                    ViewContext.Writer.Write("\"/>");
                }
            </td>
        </tr>
        <tr>
            <td class="td_value_text">
                <b>Имя пользователя:<b>
            </td>
            <td>
                @{
                    ViewContext.Writer.Write("<input type=\"text\" name=\"name\" maxlength=\"64\" size=\"32\" value=\"");
                    text = Request.Unvalidated.Form.Get("name");
                    if (text == null)
                    {
                        text = ViewBag.name;
                    }
                    ViewContext.Writer.Write(text);
                    ViewContext.Writer.Write("\"/>");
                }
            </td>
        </tr>
        <tr>
            <td class="td_value_text">
                <b>Пароль <span class="required_asterisk">*</span>:<b>
            </td>
            <td>
                @{
                    ViewContext.Writer.Write("<input type=\"text\" name=\"password\" maxlength=\"128\" size=\"32\" value=\"");
                    text = Request.Unvalidated.Form.Get("password");
                    if (text == null)
                    {
                        text = ViewBag.password;
                    }
                    ViewContext.Writer.Write(text);
                    ViewContext.Writer.Write("\"/>");
                }
            </td>
        </tr>
        <tr>
            <td class="td_value_text">
                <b>Подтверждение пароля <span class="required_asterisk">*</span>:<b>
            </td>
            <td>
                @{
                    ViewContext.Writer.Write("<input type=\"text\" name=\"password_2\" maxlength=\"128\" size=\"32\" value=\"");
                    text = Request.Unvalidated.Form.Get("password_2");
                    if (text == null)
                    {
                        text = ViewBag.password_2;
                    }
                    ViewContext.Writer.Write(text);
                    ViewContext.Writer.Write("\"/>");
                }
            </td>
        </tr>
        <tr>
            <td class="td_value_text">
                <b>Секретный вопрос:<b>
            </td>
            <td>
                @{
                    ViewContext.Writer.Write("<input type=\"text\" name=\"secret_question\" maxlength=\"128\" size=\"32\" value=\"");
                    text = Request.Unvalidated.Form.Get("secret_question");
                    if (text == null)
                    {
                        text = ViewBag.secret_question;
                    }
                    ViewContext.Writer.Write(text);
                    ViewContext.Writer.Write("\"/>");
                }
            </td>
        </tr>
        <tr>
            <td class="td_value_text">
                <b>Ответ на секретный вопрос:<b>
            </td>
            <td>
                @{
                    ViewContext.Writer.Write("<input type=\"text\" name=\"secret_answer\" maxlength=\"128\" size=\"32\" value=\"");
                    text = Request.Unvalidated.Form.Get("secret_answer");
                    if (text == null)
                    {
                        text = ViewBag.secret_answer;
                    }
                    ViewContext.Writer.Write(text);
                    ViewContext.Writer.Write("\"/>");
                }
            </td>
        </tr>
        @if ((ViewBag.Errors != null) && (ViewBag.Errors.Count != 0))
        {
            <tr>
                <td colspan="2" class="td_errors">
                    @foreach (string error in ViewBag.Errors)
                    {
                        @error<br />
                    }
                </td>
            </tr>
        }
        <tr>
            <td colspan="2" class="td_buttons">
                <input type="submit" name="ok" value="Зарегистрироваться" /><br />
                @Html.ActionLink("Авторизация", "Authorization", "Main")
            </td>
        </tr>
    </table>
</form>